plugins {
    id "com.android.application"
}

android {
    namespace "in.kiran.oms"
    compileSdk 35

    defaultConfig {
        applicationId "in.kiran.oms"
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName "2.0.0"
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
